# Site settings
title:       Dominik
email:       slaaker@126.com
author:      Dominik
description: "Cuius rei demonstrationem mirabilem sane detexi. Hanc marginis exiguitas non caperet."
baseurl:     ""
url:         "https://ds.scris.top/"

#Duoshuo short Name / 多说的shortname
duoshuo: 

#Baidu analytics / 百度统计(异步的js码，注意使用异步版本的)
baidu_analyze:  4a7701b5afbaa4089b4e2fbef17101f3
# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: scris
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
